import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';
import { AuthResponse, UpdateResponse } from 'src/app/auth/interfaces/interfaces';
import { environment } from 'src/environments/environment';
import { Vessel } from '../interfaces/mongoInter';

@Injectable({
  providedIn: 'root'
})
export class MongoService {

  private baseUrl: string = environment.baseUrl;
  names: string[] = ["ADMIRAL",
  "AGUILA DORADA",
  "AGUILA IMPERIAL",
  "AGUILA MARINA",
  "ALBATROS",
  "ALICE G MCCALL",
  "ALIOTH",
  "ALLISON",
  "ALTAMIRA",
  "ALVARADO",
  "AMPARO PAOLA",
  "ANDROMEDA",
  "ANNY MV",
  "ANTARES",
  "AQUA PACIFIC",
  "ARBOL GRANDE",
  "ARCANGEL SAN GABRIEL",
  "ARCANGEL SAN RAFAEL",
  "ATALAYA",
  "ATLAS",
  "AVE FENIX",
  "AZTECA 1",
  "AZTECA 10",
  "AZTECA 2",
  "AZTECA 3",
  "AZTECA 4",
  "AZTECA 5",
  "AZTECA 6",
  "AZTECA 7",
  "AZTECA 8",
  "AZTECA 9",
  "B-1",
  "BACO",
  "BAHIA DE CAMPECHE",
  "BAHIA DEL ESPIRITU SANTO",
  "BAJA STAR",
  "BAKAM",
  "BALLENA II",
  "BALTIC",
  "BELUGA 1",
  "BELUGA 2",
  "BENCHO",
  "BERJAYA",
  "BERNIE MCCALL",
  "BICENTENARIO",
  "BIENVILLE",
  "BLUE COMMANDER",
  "BLUE FALCON",
  "BLUE GIANT",
  "BLUE HAWK",
  "BLUE PHOENIX",
  "BLUE PIONEER",
  "BLUE STAR",
  "BLUE SWIFT",
  "BLUEFIN",
  "BOURBON ALIENOR",
  "BOURBON ARTABAZE",
  "BOURBON ARTEMIS",
  "BUCANERO",
  "BUFFALO RIVER",
  "BUQUE OCEANOGRAFICO ALPHA HELIX",
  "BURGOS",
  "C-VIKING",
  "C-WARRIOR",
  "CABO ROJO",
  "CALAKMUL",
  "CALETA",
  "CAMILA",
  "CAMPECHE",
  "CANOPUS",
  "CAPE LOOKOUT",
  "CAPE SABLE",
  "CAPT. BILL III",
  "CAPT. JOHN",
  "CARIBE III",
  "CARMEN III",
  "CARSON RIVER",
  "CARTAGONOVA",
  "CASTOR",
  "CENTENARIO",
  "CENTLA",
  "CERRO AZUL",
  "CERRO DE LA PEZ",
  "CERRO DEL TEPEYAC",
  "CHARTRES",
  "CHEMUL",
  "CHICONTEPEC",
  "CHIRON",
  "CINDY TIDE",
  "CMM CENTENARIO",
  "CMM CHAPULIN",
  "CMM CORDOBES",
  "CMM CORSARIO",
  "CMM JAROCHO",
  "CMM MAGUEY",
  "CMM MARIACHI",
  "CMM MEZCAL",
  "CMM OAXACA",
  "CMM TABASCO",
  "CMM TEQUILA",
  "CMM VERACRUZ",
  "COATZACOALCOS",
  "COBOS",
  "CONDOR II",
  "COSALA",
  "COSMOS 3",
  "COSMOS-2",
  "CREST BAZAN 1",
  "CREST BAZAN 2",
  "CREST TARASCO",
  "CROSBY COMMODORE",
  "CTOY",
  "CUAUHTEMOC",
  "DABHOL",
  "DELTA",
  "DENEB",
  "DEVILLE TIDE",
  "DOMINATOR",
  "DON ALEJANDRO",
  "DON ALEX",
  "DON BENJAMIN",
  "DON CARLOS",
  "DON DANIEL T.",
  "DON ENRIQUE II",
  "DON FELIPE",
  "DON FILI",
  "DON IGNACIO",
  "DON J. RAGLAND",
  "DON JOAQUIN",
  "DON JULIO M.",
  "DON LUIS",
  "DON MIGUEL G.",
  "DON OSIRIS R. R.",
  "DON ROBERTO",
  "DON RODOLFO M.",
  "DON VICENTE",
  "DONA ANGELA MARIA T.",
  "DONA ANGELES",
  "DONA BLANCA",
  "DONA CONCHITA",
  "DONA DIANA",
  "DONA HILDA",
  "DONA LOURDES",
  "DONA PAULA",
  "DONA SILVIA",
  "DONA TERE",
  "DOREEN MCCALL",
  "DR JORGE CARRANZA FRASER",
  "ECO III",
  "EL DORADO",
  "EL DUQUE",
  "EL HUASTECO",
  "EL MEZQUITAL",
  "EL PATRON",
  "EL PUMA",
  "ENAV SAGUARO",
  "FARIDAH",
  "FELTON TIDE",
  "FENIX",
  "FIREHOLE RIVER",
  "FLECHA DE ORO",
  "FLOKI",
  "FRANZ",
  "GALEM I",
  "GALEM II",
  "GANNET",
  "GARZPROM-2",
  "GEMINIS",
  "GIJON",
  "GIS VAYDA",
  "GLADIATOR",
  "GLEIXNER TIDE",
  "GLOBAL EXPLORER",
  "GLORIA ELENA",
  "GLORY",
  "GO CANOPUS",
  "GOIMAR 703",
  "GOIMAR 905",
  "GOIMAR 906",
  "GOLFA III",
  "GOLIATH",
  "GREENWOOD TIDE",
  "GULF MARINER",
  "HAI YANG SHI YOU 614",
  "HAMMERHEAD",
  "HANNA",
  "HARVEY CLIPPER",
  "HARVEY HURRICANE",
  "HARVEY LEADER",
  "HARVEY LEGEND",
  "HAYDEN",
  "HEBERT TIDE",
  "HERCULES",
  "HERMON KING",
  "HOS BRIGADOON",
  "HOS BROWNING",
  "HOS COLT",
  "HOS CORAL",
  "HOS CRESTVIEW",
  "HOS DAKOTA",
  "HOS IRON HORSE",
  "HOS REMINGTON",
  "HOS RENAISSANCE",
  "HOS RIDGEWIND",
  "HOS SILVER ARROW",
  "HOS SWEET WATER",
  "HOS THUNDERFOOT",
  "HOS WINCHESTER",
  "HUNTER",
  "IGNACIO ALLENDE",
  "IMILOA",
  "INDEPENDENCIA",
  "INDEPENDENCIA 1",
  "ISLA ARBOLEDA",
  "ISLA AZTECA",
  "ISLA BLANCA",
  "ISLA CIARI",
  "ISLA CRECIENTE",
  "ISLA DE CEDROS",
  "ISLA GRANDE",
  "ISLA JANITZIO",
  "ISLA LEON",
  "ISLA MIRAMAR",
  "ISLA MONSERRAT",
  "ISLA PASSAVERA",
  "ISLA SAN GABRIEL",
  "ISLA SAN IGNACIO",
  "ISLA SAN JOSE",
  "ISLA SAN LUIS",
  "ISLA SANTA CRUZ",
  "ISLA VERDE",
  "JAGUAROUNDI",
  "JESUS",
  "JOSE MARIA MORELOS II",
  "JUAN PABLO",
  "JUAN PABLO II",
  "JUAREZ",
  "JUSTO SIERRA",
  "KIN",
  "KUKULCAN",
  "LA BAMBA",
  "LADY BARBARA",
  "LADY DI T",
  "LADY ELIZABETH",
  "LADY IONE",
  "LAGERTHA",
  "LAGUNERO",
  "LEIBE TIDE",
  "LEO",
  "LINDA F",
  "LISA F",
  "LLUAVI",
  "LOUSTEAU TIDE",
  "LULUSA",
  "M AMELIA",
  "MANZANILLO",
  "MAR DE CORTES",
  "MARA",
  "MARIA BEATRIZ",
  "MARIA DELIA",
  "MARIA LUISA",
  "MARIANO ABASOLO",
  "MARINA ORION",
  "MARIS",
  "MAURICIO",
  "MAZATL",
  "MAZATUN",
  "MAZPESCA 2",
  "MERCURIO",
  "MEXICO III",
  "MEXICO IV",
  "MEXICO STAR",
  "MEXICO V",
  "MEXTUG BALSAS",
  "MEXTUG LERMA",
  "MIGUEL HIDALGO II",
  "MILLER TIDE",
  "MINERAL",
  "MITCHELL",
  "MONFORTE DE LEMOS",
  "MR SAM",
  "MR. DOUG",
  "NAIR II",
  "NATALIE",
  "NAUTLA",
  "NN ALGEIBA",
  "NN CHORT",
  "NN LEONIS",
  "NN REGULUS",
  "NN SUBRA",
  "OAXACA",
  "OAXACA STAR",
  "OCEAN STAR",
  "OFFSHORETAXI ONE",
  "OLIMPO",
  "ORION I",
  "PACO C",
  "PANAMAX ALEXANDER",
  "PAPALOAPAN",
  "PAT TAYLOR",
  "PEMEX CELESTUN",
  "PEMEX EHECATL",
  "PEMEX HUASTECO",
  "PEMEX HUICHOL",
  "PEMEX MIXTECO",
  "PEMEX TARAHUMARA",
  "PEMEX TEPEHUANO",
  "PEMEX TLALOC",
  "PEMEX TOTONACA",
  "PEMEX XLVII",
  "PERLA DEL GOLFO",
  "PERSUADER I",
  "PETROIL 2",
  "PIONERO",
  "POLARIS",
  "POLLUX",
  "PREDATOR",
  "PROCYON",
  "PROTEUS",
  "PUNTA DELGADA",
  "PUNTA JEREZ",
  "PUNTILLA",
  "REDFIN",
  "REDFISH 4",
  "REFORMA PEMEX",
  "REVOLUCION",
  "RIO BALSAS",
  "ROCA PARTIDA",
  "ROLLO",
  "ROZO TIDE",
  "RPM COLIMA",
  "RPM CUYUTLAN",
  "RPM MANZANILLO",
  "RPM TEPALCATES",
  "S. FLORIANA",
  "SAAM AZTECA",
  "SAAM AZTLAN",
  "SAAM CHONTAL",
  "SAAM CITLALI",
  "SAAM CORA",
  "SAAM HUASTECA",
  "SAAM HUICHOL",
  "SAAM JAROCHO",
  "SAAM KABAH",
  "SAAM MIXTECO",
  "SAAM OTOMI",
  "SAAM QUETZAL",
  "SAAM RARAMURI",
  "SAAM TACUATE",
  "SAAM TAJIN",
  "SAAM TEPEYAC",
  "SAAM TLALOC",
  "SAAM TULUM",
  "SAAM UXMAL",
  "SAAM ZAPOTECA",
  "SABALO",
  "SAKIS P",
  "SAN GUILLERMO",
  "SAN JORGE",
  "SAN RAFAEL",
  "SANDUNGA",
  "SANTA MARCELA",
  "SATURNO",
  "SEACOR AZTECA",
  "SEACOR CABRAL",
  "SEACOR COLUMBUS",
  "SEACOR MARLIN",
  "SEACOR MAYA",
  "SEACOR OLMECA",
  "SEACOR PRIDE",
  "SEACOR TOLTECA",
  "SEACOR VIKING",
  "SEACOR WARRIOR",
  "SERGIO GRACIA AGUILAR",
  "SIRIUS",
  "SMBC MEXICALI",
  "SMBC MONTERREY",
  "SMBC ROSARITO",
  "SMBC TIJUANA",
  "SMS CAMPECHE",
  "SOCORRO VORTEX",
  "SPICA",
  "SPIRIT",
  "STIM STAR CAMPECHE",
  "STIM STAR MEXICO",
  "SUSAN",
  "SVITZER CHEMUL",
  "SWIBER ADA",
  "SWIBER OSLO",
  "SWIBER QUETZAL",
  "SWIFT",
  "TA'KUNTAH",
  "TAMARA",
  "TAMIAHUA",
  "TAMPICO",
  "TANOK",
  "TAURO",
  "TEHUANA",
  "TENABO",
  "TEPAL CHEEM",
  "TEXISTEPEC",
  "THUNDERSTAR",
  "TILA",
  "TOLTECA",
  "TOMY",
  "TOPAZ CAPTAIN",
  "TRANSCARIBE I",
  "TROPIC SCOUT",
  "TULA",
  "TULUM",
  "TURQUOISE",
  "TUXPAN",
  "TYR",
  "ULTRACARGA I",
  "ULTRACARGA III",
  "ULTRACARGA IV",
  "ULTRAMAR IV",
  "UP AGATE",
  "UP JADE",
  "UP TURQUOISE",
  "V.B. ATLANTICO",
  "V.B. CHIHUAHUA",
  "V.B. CORAL",
  "V.B. PACIFICO",
  "V.B. SINALOA",
  "V.B. SONORA",
  "V.B. TAMAULIPAS",
  "VB CAMPEADOR",
  "VB GLORIOSO",
  "VB JALISCO",
  "VB YUCATAN",
  "VICENTE GUERRERO II",
  "VICTORIA",
  "VIGO",
  "XCARET",
  "XICALANGO",
  "XIKIM",
  "YACATECUTLI",
  "YELLOWFIN",
  "ZACATAL",
  "ZAPOTITLAN",
  ]
  constructor(private http: HttpClient) { }

  getCoors( Vessel_Name: string ) {

    const url  = `${ this.baseUrl }/elements`;
    const body = { Vessel_Name };

    return this.http.post<AuthResponse>( url, body )
      .pipe(
        tap( resp => {
          if (resp.ok) {

          }
        }),
        map( resp => resp.msg ),
        catchError( err => of(err.error.msg) )
      );
  }

  updateCoors( Vessel_Name: string ) {

    const url  = `${ this.baseUrl }/elements/scrap`;
    const body = { Vessel_Name };

    return this.http.put<UpdateResponse>( url, body )
      .pipe(
        tap( resp => {
          if (resp.ok) {
          }
        }),
        map( resp => resp.msg ),
        catchError( err => of(err.error.msg) )
      );
  }

}
